// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct Message {
    pub id: i32,
    pub sender_id: i32,
    pub receiver_id: Option<i32>,
    pub channel_id: Option<i32>,
    pub content: String,
    pub timestamp: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub password: String,
    pub skill_level: i32,
    pub preferred_climbing_style: Option<String>,
    pub preferred_gym: Option<String>,
}

